TYPO3-Headless/nuxt-typo3

lib/templates/components/content/elements/media/Gallery.vue
=> fix(ce): support intext option for gallery content element

lib/types.d.ts, package.json
=> refactor(general): add typescript definitions

lib/templates/pages/_.vue
=> fix(layouts): remove uselsess <h1/> tag

example/layouts/error.vue, lib/templates/middleware/context.js
=> feat(layouts): add page content for error pages (#19)

lib/templates/lib/api.js, lib/templates/plugins/api.js, lib/templates/plugins/i18n.js
=> 32 fix current locale multiple dmains

docs/.vuepress/config.js, docs/configuration/static-generate.md, test/module.test.js
=> 37 doc static generate

lib/module.js, lib/templates/components/content/elements/CeForm_formframework.vue, lib/templates/plugins/forms.js, package.json, test/module.test.js, yarn.lock
resolves #41, 
to enable it - just pass `registerForm: true` to nuxt-typo3 options. 
What should be done - waiting for backend:
https://github.com/TYPO3-Initiatives/headless/issues/79
1. Multiple steps
2. Confirmation message should be returned by backend 
3. Submit button labels missing 
4. Check connection with languages
=> feat(ce): form component proof of concept

lib/module.js, package.json, yarn.lock
=> refactor(deps): replace lodash.merge with defu #45

lib/templates/mixins/seo/getMeta.js
#resolve 39
Just leave some footprint for pages generated with this solution 😄
=> feat: add generator meta tag (#39)

lib/templates/middleware/context.js
=> Missing check is response object even exists.

CHANGELOG.md, lib/templates/mixins/seo/getMeta.js, package.json
=> 61 fix canonicals

lib/templates/components/content/CeDynamic.js, lib/templates/components/content/CeRenderer.js
I added iteration index for CeRenderer, and CeDynamic. Now you can define index props in content elements to get its iteration index in colPos.
=> feat: add iteration index for content elements

lib/module.js, lib/templates/lib/api.js, lib/templates/lib/logger.js
=> fix: avoid warning in standalone build

lib/options.js, lib/templates/lib/api.js, lib/templates/plugins/api.js
=> fix: initialData fallback loop

lib/templates/components/utilities/NavLink.vue
=> fix: remove tag props from navlink

.eslintrc.js, example/plugins/components.js, lib/templates/plugins/components.js
=> refactor: remove app reference

docs/package.json, docs/yarn.lock
bump alertbot about  security vulnerabilities in docs packages
=> chore(deps): bump alertbot packages for docs

docs/package.json, docs/yarn.lock
update dependencies in docs workspace
=> chore(deps): bump docs dependencies

lib/templates/components/utilities/NavLink.vue
=> 131 fix navlink

docs/README.md, docs/from-scratch.md, docs/getting-started.md
Just some minor grammar fixes for the top-level files "Readme", "From Scratch", and "Getting Started".
=> [Docs] Grammar fixes

lib/templates/mixins/seo/getMeta.js
added social media meta tags and more
=> fix: Meta tags improvement #9

lib/templates/components/content/elements/media/type/Image.vue
title isn't defined, which leads to the error that no title attribute is shown
=> Remove title as it isn't defined

lib/mixins/seo/getMeta.js
=> fix: fix canonical URL path

README.md, docs/getting-started.md, lib/module.js
=> feat: enable store in runtime (#198)

docs/frontend/forms.md, example/nuxt.config.js, lib/module.js, lib/options.js, lib/plugins/components.js, lib/plugins/layouts.js, lib/types.d.ts
resolve #202 
BREAKING CHANGE:
configuration schema update
- renamed registerComponents to components
- removed registerLayouts - now this is only one component - default
- renamed registerForms to forms
=> refactor!: update configuration fields

docs/frontend/forms.md, example/components/FormFieldTemplate.vue, example/nuxt.config.js, lib/components/T3CeFormFormframework/T3CeFormFormframework.vue, lib/components/T3CeFormFormframework/__tests__/T3FormFormframework.data.json, lib/components/T3CeFormFormframework/__tests__/T3FormFormframework.spec.js, lib/components/T3Form/T3Form.vue, lib/components/T3Form/T3FormField/T3FormField.vue, lib/components/T3Form/T3FormFieldList/T3FormFieldList.vue, lib/components/T3Form/T3FormValidators.js, lib/components/T3Form/__tests__/T3Form.data.json, package.json
resolve #207, the nice idea will be adding more unit tests, but at this moment we can go with what we have
=> separate ui form elements props from t3formframework 

lib/components/T3CeFormFormframework/__tests__/T3FormFormframework.spec.js, lib/components/T3Form/T3FormFieldList/T3FormFieldList.vue, lib/components/T3Form/__tests__/T3Form.data.json, lib/components/T3Form/__tests__/T3Form.spec.js
=> fix(forms): reset multiple models (#210)

lib/components/T3BlDefault/T3BlDefault.vue, lib/components/T3Dynamic/T3Dynamic.js
=> fix: add Array type for empty pages (#218)

lib/components/T3CeFeloginLogin/T3CeFeloginLogin.vue, lib/store/index.js, lib/store/mutations.js
=> feat: handle user state based on initialData

lib/components/T3CeFeloginLogin/T3CeFeloginLogin.vue
=> fix: use typo3 prefix in store action (#232)

lib/components/T3NavLink/T3NavLink.spec.js, lib/components/T3NavLink/T3NavLink.vue
=> 305 fix navlink

lib/lib/context.js
=> fix: route middleware for client mode (#306)
